TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 32
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: /pasteur/results/slowfast/models/swin_base_patch244_window877_kinetics400_1k.pth
  CHECKPOINT_EPOCH_RESET: True
DATA:
  PATH_TO_DATA_DIR: /pasteur/data/slowfast/datasets/kinetics10
  PATH_PREFIX: /pasteur/data/slowfast/datasets/kinetics10
  PATH_TO_PRELOAD_IMDB: /pasteur/data/slowfast/datasets/kinetics10
  IMDB_FILES:
    TRAIN: ['train']
    VAL: ['val']
    TEST: ['test']
  DECODING_BACKEND: pyav
  NUM_FRAMES: 8
  SAMPLING_RATE: 32
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
AUG:
  ENABLE: True
  AA_TYPE: rand-m9-mstd0.5-inc1
  COLOR_JITTER: 0.4
  RE_COUNT: 1
  RE_PROB: 0.25
SWIN:
  DEPTHS: [2, 2, 18, 2]
  EMBED_DIM: 128
  PATCH_NORM: True
  FROZEN_STAGES: -1
  WINDOW_SIZE: (8, 7, 7)
  PATCH_SIZE: (2, 4, 4) 
  NUM_HEADS: [4, 8, 16, 32]
  IN_CHANS: 3
  MLP_RATIO: 4.0
  QKV_BIAS: True
  QK_SCALE: None
  DROP_RATE: 0.0
  ATTN_DROP_RATE: 0.0
  DROP_PATH_RATE: 0.2
  DROP_HEAD: 0.5
  NORM_LAYER: layernorm
  SPATIAL_TYPE: avg
SOLVER:
  BASE_LR: 0.001
  LR_POLICY: cosine
  MAX_EPOCH: 40
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: SwinTransformer3D
  NUM_CLASSES: 10
  ARCH: vit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 8
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: True
  SYNC_WANDB: True
  LOG_DIR: logs
  CLASS_NAMES_PATH: /pasteur/data/slowfast/datasets/kinetics10/classnames.json
  CONFUSION_MATRIX:
    ENABLE: True
  SAMPLE_VIS:
    ENABLE: True
    LOG_PERIOD: 1000
  DIST_VIS:
    ENABLE: True
    LOG_PERIOD: 1000
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /pasteur/results/slowfast/kinetics/Kinetics10_Sup_Swin128_run0
LOG_MODEL_INFO: False
