TRAIN:
  ENABLE: True
  DATASET: imagenet
  BATCH_SIZE: 256
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: /pasteur/u/mottaghi/models/swinv2_tiny_patch4_window8_256.pth
  CHECKPOINT_EPOCH_RESET: True
  MIXED_PRECISION: False
DATA:
  PATH_TO_DATA_DIR: /pasteur/u/mottaghi/datasets/office_home
  PATH_PREFIX: /pasteur/u/mottaghi/datasets/office_home
  PATH_TO_PRELOAD_IMDB: /pasteur/u/mottaghi/datasets/office_home
  IMDB_FILES:
    TRAIN: ['Real_World']
    VAL: ['Product']
    TEST: ['Product']
  TRAIN_CROP_SIZE: 256
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
AUG:
  ENABLE: True
  AA_TYPE: rand-m10-n2-mstd2.0-inc1
  COLOR_JITTER: 0.4
  GRAYSCALE: 0.2
  GAUSSIAN_BLUR: 0.5
  RE_COUNT: 1
  RE_PROB: 0.25
SWIN:
  DEPTHS: [2, 2, 6, 2]
  EMBED_DIM: 96
  PATCH_NORM: True
  FROZEN_STAGES: -1
  WINDOW_SIZE: (8, 8)
  PATCH_SIZE: (4, 4) 
  NUM_HEADS: [3, 6, 12, 24]
  IN_CHANS: 3
  MLP_RATIO: 4.0
  QKV_BIAS: True
  QK_SCALE: None
  DROP_RATE: 0.0
  ATTN_DROP_RATE: 0.0
  DROP_PATH_RATE: 0.2
  DROP_HEAD: 0.5
  NORM_LAYER: layernorm
  SPATIAL_TYPE: avg
  FEW_SHOT: True
  TEMP: 0.07
SOLVER:
  BASE_LR: 0.05
  LR_POLICY: cosine
  WARMUP_START_LR: 0.0
  WARMUP_EPOCHS: 10.0
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: SwinTransformerV2
  NUM_CLASSES: 65
  ARCH: vit
  LOSS_FUNC: cross_entropy
TEST:
  ENABLE: True
  DATASET: imagenet
  BATCH_SIZE: 8
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: True
  SYNC_WANDB: True
  LOG_DIR: logs
  CLASS_NAMES_PATH: /pasteur/u/mottaghi/datasets/office_home/classnames.json
  CONFUSION_MATRIX:
    ENABLE: True
    FIGSIZE: [30, 30]
  HISTOGRAM:
    FIGSIZE: [30, 30]
  DIST_VIS:
    ENABLE: True
    LOG_PERIOD: 1000
  SAMPLE_VIS:
    ENABLE: True
    LOG_PERIOD: 1000
ADAPTATION:
  ENABLE: True
  ADAPTATION_TYPE: 'AdaEmbed'
  SOURCE: ['Real_World']
  TARGET: ['Product']
  ALPHA: 0.125
  BETA: 1.0
  BANK_SIZE: 1000
  SEMI_SUPERVISED:
    ENABLE: False
    NUM_SHOTS: 3
ADAEMBED:
  LAMBDA_H: 0.2
  LAMBDA_T: 0.0
  LAMBDA_P: 0.0
  LAMBDA_C: 0.0
  TEMP: 0.05
  EMA: 0.95
  TAU: 0.9
  NUM_NEIGHBORS: 10
  PSEUDO_TYPE: AdaEmbed
  THRESHOLDING: relative
  ALIGNMENT: True
  SAMPLING: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /pasteur/u/mottaghi/logs/office_home/R2P_MME_Run1
LOG_MODEL_INFO: False
