TRAIN:
  ENABLE: True
  DATASET: imagenet
  BATCH_SIZE: 864
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: /pasteur/u/mottaghi/models/swin_tiny_patch4_window7_224.pth
  CHECKPOINT_EPOCH_RESET: True
DATA:
  PATH_TO_DATA_DIR: /pasteur/u/mottaghi/datasets/domainnet
  PATH_PREFIX: /pasteur/u/mottaghi/datasets/domainnet
  PATH_TO_PRELOAD_IMDB: /pasteur/u/mottaghi/datasets/domainnet
  IMDB_FILES:
    TRAIN: ['painting']
    VAL: ['real']
    TEST: ['real']
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
AUG:
  ENABLE: True
  AA_TYPE: rand-m10-n2-mstd2.0-inc1
  COLOR_JITTER: 0.4
  RE_COUNT: 1
  RE_PROB: 0.25
SWIN:
  DEPTHS: [2, 2, 6, 2]
  EMBED_DIM: 96
  PATCH_NORM: True
  FROZEN_STAGES: -1
  WINDOW_SIZE: (7, 7)
  PATCH_SIZE: (4, 4) 
  NUM_HEADS: [3, 6, 12, 24]
  IN_CHANS: 3
  MLP_RATIO: 4.0
  QKV_BIAS: True
  QK_SCALE: None
  DROP_RATE: 0.0
  ATTN_DROP_RATE: 0.0
  DROP_PATH_RATE: 0.2
  DROP_HEAD: 0.5
  NORM_LAYER: layernorm
  SPATIAL_TYPE: avg
SOLVER:
  BASE_LR: 0.05
  LR_POLICY: cosine
  MAX_EPOCH: 40
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: SwinTransformer
  NUM_CLASSES: 126
  ARCH: vit
  LOSS_FUNC: cross_entropy
TEST:
  ENABLE: True
  DATASET: imagenet
  BATCH_SIZE: 8
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: True
  SYNC_WANDB: True
  LOG_DIR: logs
  CLASS_NAMES_PATH: /pasteur/u/mottaghi/datasets/domainnet/classnames.json
  CONFUSION_MATRIX:
    ENABLE: True
    FIGSIZE: [30, 30]
  HISTOGRAM:
    FIGSIZE: [30, 30]
  DIST_VIS:
    ENABLE: True
    LOG_PERIOD: 1000
  SAMPLE_VIS:
    ENABLE: True
    LOG_PERIOD: 1000
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /pasteur/u/mottaghi/logs/domainnet/P2R_Sup_Swin96_run0
LOG_MODEL_INFO: False
