TRAIN:
  ENABLE: True
  DATASET: imagenet
  BATCH_SIZE: 80
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: /pasteur/results/slowfast/domainnet/P2R_Sup_Swin128_run0/checkpoints/checkpoint_epoch_00040.pyth
  CHECKPOINT_EPOCH_RESET: True
DATA:
  PATH_TO_DATA_DIR: /pasteur/data/slowfast/datasets/domainnet
  PATH_PREFIX: /pasteur/data/slowfast/datasets/domainnet
  PATH_TO_PRELOAD_IMDB: /pasteur/data/slowfast/datasets/domainnet
  IMDB_FILES:
    TRAIN: ['painting']
    VAL: ['real']
    TEST: ['real']
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
AUG:
  ENABLE: True
  AA_TYPE: rand-m10-n2-mstd0.5-inc1
  COLOR_JITTER: 0.4
  RE_COUNT: 1
  RE_PROB: 0.25
SWIN:
  DEPTHS: [2, 2, 18, 2]
  EMBED_DIM: 128
  PATCH_NORM: True
  FROZEN_STAGES: -1
  WINDOW_SIZE: (7, 7)
  PATCH_SIZE: (4, 4) 
  NUM_HEADS: [4, 8, 16, 32]
  IN_CHANS: 3
  MLP_RATIO: 4.0
  QKV_BIAS: True
  QK_SCALE: None
  DROP_RATE: 0.0
  ATTN_DROP_RATE: 0.0
  DROP_PATH_RATE: 0.2
  DROP_HEAD: 0.5
  NORM_LAYER: layernorm
  SPATIAL_TYPE: avg
SOLVER:
  BASE_LR: 0.001
  LR_POLICY: cosine
  MAX_EPOCH: 40
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: SwinTransformer
  NUM_CLASSES: 126
  ARCH: vit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: imagenet
  BATCH_SIZE: 8
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: True
  SYNC_WANDB: True
  LOG_DIR: logs
  CLASS_NAMES_PATH: /pasteur/data/slowfast/datasets/domainnet/classnames.json
  CONFUSION_MATRIX:
    ENABLE: True
  SAMPLE_VIS:
    ENABLE: True
    LOG_PERIOD: 1000
  DIST_VIS:
    ENABLE: True
    LOG_PERIOD: 1000
ADAPTATION:
  ENABLE: True
  ADAPTATION_TYPE: 'AdaMatch'
  SOURCE: ['painting']
  TARGET: ['real']
  ALPHA: 0.1
  BETA: 1.0
  SEMI_SUPERVISED:
    ENABLE: False
    NUM_SHOTS: 3
ADAMATCH:
  ALPHA: 1
  MU: 1.0
  THRESHOLDING:
    ENABLE: True
    TYPE: uniform
    TAU: 0.9
  ALIGNMENT:
    ENABLE: True
  SAMPLING:
    ENABLE: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /pasteur/results/slowfast/domainnet/P2R_AdaMatch_Swin128_run0
LOG_MODEL_INFO: False
